### ISSUE TITLE
THREADSTACK0 address for process

### ISSUE THREAD

**Issue by tqwewe** [sy1ntexx/faithe#2]
When working with cheatengine, you can come across a token called `THREADSTACK0`.

`THREADSTACK0` is explained here: https://forum.cheatengine.org/viewtopic.php?p=5487976#5487976

Does this library have anything similar to address offsets for modifying memory after game restarts?

**Comment by sy1ntexx** [comment]
You can use https://docs.rs/faithe/0.8.0/faithe/memory/fn.follow_pointer_path.html to address multilevel pointers.

**Comment by sy1ntexx** [comment]
Tell me if this is what you were looking for
